"""agent-taskstate source package."""

from .typed_ref import (
    TypedRef,
    canonicalize_ref,
    format_ref,
    is_known_domain,
    is_valid_ref,
    memx_ref,
    parse_ref,
    tracker_ref,
    validate_ref,
    agent_taskstate_ref,
)

from .state_transition import (
    StateTransition,
    StateTransitionService,
    InvalidTransitionError,
    TerminalStateError,
    MissingReasonError,
    can_transition,
    is_terminal,
    requires_reason,
    ALLOWED_TRANSITIONS,
    TERMINAL_STATES,
)

from .transition_config import (
    TransitionConfig,
    DEFAULT_CONFIG,
    get_config,
    reload_config,
)

from .context_bundle import (
    ContextBundle,
    BundleSource,
    ContextBundleService,
    ContextRebuildService,
    REBUILD_LEVELS,
    PURPOSE_TYPES,
    SOURCE_KINDS,
    compress_json,
    decompress_json,
    compute_diff,
    decompress_bundle_json,
    COMPRESSION_THRESHOLD,
)

from .resolver import (
    ContextRebuildResolver,
    ResolveStatus,
    ResolvedRef,
    ResolveReport,
    SummaryPayload,
    RawPayload,
    ResolverDiagnostics,
    AgentTaskstateLocalResolver,
    TrackerResolver,
    MemxResolver,
    RAW_DESCENT_CONDITIONS,
)

from .tracker_bridge import (
    TrackerBridgeService,
    TrackerConnection,
    IssueCache,
    EntityLink,
    SyncEvent,
    IssueSnapshot,
    SyncSuggestion,
    SyncDirection,
    SyncStatus,
    LinkRole,
    MockTrackerAdapter,
    GitHubAdapter,
    JiraAdapter,
    create_tracker_tables,
)

__all__ = [
    # typed_ref
    "TypedRef",
    "canonicalize_ref",
    "format_ref",
    "is_known_domain",
    "is_valid_ref",
    "memx_ref",
    "parse_ref",
    "tracker_ref",
    "validate_ref",
    "agent_taskstate_ref",
    # state_transition
    "StateTransition",
    "StateTransitionService",
    "InvalidTransitionError",
    "TerminalStateError",
    "MissingReasonError",
    "can_transition",
    "is_terminal",
    "requires_reason",
    "ALLOWED_TRANSITIONS",
    "TERMINAL_STATES",
    # transition_config
    "TransitionConfig",
    "DEFAULT_CONFIG",
    "get_config",
    "reload_config",
    # context_bundle
    "ContextBundle",
    "BundleSource",
    "ContextBundleService",
    "ContextRebuildService",
    "REBUILD_LEVELS",
    "PURPOSE_TYPES",
    "SOURCE_KINDS",
    "compress_json",
    "decompress_json",
    "compute_diff",
    "decompress_bundle_json",
    "COMPRESSION_THRESHOLD",
    # resolver
    "ContextRebuildResolver",
    "ResolveStatus",
    "ResolvedRef",
    "ResolveReport",
    "SummaryPayload",
    "RawPayload",
    "ResolverDiagnostics",
    "AgentTaskstateLocalResolver",
    "TrackerResolver",
    "MemxResolver",
    "RAW_DESCENT_CONDITIONS",
    # tracker_bridge
    "TrackerBridgeService",
    "TrackerConnection",
    "IssueCache",
    "EntityLink",
    "SyncEvent",
    "IssueSnapshot",
    "SyncSuggestion",
    "SyncDirection",
    "SyncStatus",
    "LinkRole",
    "MockTrackerAdapter",
    "GitHubAdapter",
    "JiraAdapter",
    "create_tracker_tables",
]
